/**
 * Authentication flow for the collection.
 *
 * The goal is that, after importing the collection, the user fills in their
 * credentials once in the environment, runs Login, and everything else works
 * without touching the token again.
 *
 * `attachLoginAutoToken` used to exist, but in practice it never activated
 * (measured: 0 of 11 example projects) for two reasons:
 *
 *   1. It required a manually configured `tokenResponsePath` and exited through
 *      the back door with `if (!tokenPath) return;`.
 *   2. It searched for the login endpoint by comparing the item's NAME against
 *      ["login", "authenticate", …], while the names generated by the
 *      builder are "Create Login", "/POST auth/login", "/api_login"…
 *
 * Here, login is detected by method + URI, which is stable across frameworks,
 * and the script tries the usual response paths at runtime instead of
 * requiring them to be declared.
 */
import type {
  PostmanCollection,
  PostmanItem,
} from "../../contracts/interfaces/core/postman.interface.js";
import type { IAuthFlow } from "../../contracts/interfaces/core/discovery.interface.js";
import type { IApplyAuthFlowOptions } from "../../contracts/interfaces/core/domain.interface.js";
import type { IMissingCredentialsWarning } from "../../contracts/interfaces/cli/auth-warning.interface.js";
import { AUTH_PASSWORD_VARIABLE, AUTH_TOKEN_VARIABLE, AUTH_USERNAME_VARIABLE } from "../../contracts/constants/core/auth.constant.js";

/** URI suffixes that identify each step in the cycle. */
const LOGIN_URI_PATTERNS = [
  /\/login\/?$/i,
  /\/signin\/?$/i,
  /\/sign-in\/?$/i,
  /\/authenticate\/?$/i,
  /\/auth\/token\/?$/i,
  /\/oauth\/token\/?$/i,
  /\/sessions?\/?$/i,
];

/**
 * If the project exposes a session endpoint, based on the specs.
 *
 * `detectAuthFlow` answers the same question but for the **already-built
 * collection**, and some callers need to know before building it: the
 * authentication scheme determines which headers each request carries, so it
 * cannot be resolved afterward.
 *
 * It intentionally shares patterns with `detectAuthFlow`. If two lists of
 * login routes drift, the collection could say there is bearer while the flow
 * wires no token, or the other way around.
 */
export function hasLoginEndpoint(
  specs: ReadonlyArray<{ method: string; uri: string }>,
): boolean {
  return specs.some(
    (s) =>
      s.method.toUpperCase() === "POST" &&
      LOGIN_URI_PATTERNS.some((re) => re.test(s.uri)),
  );
}
const REFRESH_URI_PATTERNS = [/\/refresh\/?$/i, /\/auth\/refresh\/?$/i, /\/token\/refresh\/?$/i];
const LOGOUT_URI_PATTERNS = [/\/logout\/?$/i, /\/signout\/?$/i, /\/sign-out\/?$/i];

/**
 * Paths where the token usually appears in the response, in order of
 * probability. The script tries all of them at runtime: it is more robust
 * than asking the user to figure out which one applies.
 */
const TOKEN_RESPONSE_PATHS = [
  "access_token",
  "token",
  "accessToken",
  "data.access_token",
  "data.token",
  "data.accessToken",
  "jwt",
  "id_token",
];

/** Fields in the login body that represent the username. */
const USERNAME_FIELDS = ["email", "username", "user", "login", "correo", "usuario"];
/** Fields in the login body that represent the password. */
const PASSWORD_FIELDS = ["password", "passwd", "pass", "secret", "contrasena", "contraseña"];

/**
 * Locates the login, refresh, and logout endpoints in the collection.
 * Returns `null` if the project has none.
 */
export function detectAuthFlow(collection: PostmanCollection): IAuthFlow | null {
  const requests = [...eachRequest(collection.item ?? [])];

  const login = requests.find((i) => matchesAny(i, LOGIN_URI_PATTERNS, ["POST"])) ?? null;
  const refresh = requests.find((i) => matchesAny(i, REFRESH_URI_PATTERNS, ["POST"])) ?? null;
  const logout =
    requests.find((i) => matchesAny(i, LOGOUT_URI_PATTERNS, ["POST", "GET", "DELETE"])) ?? null;

  if (!login && !refresh && !logout) return null;
  return { login, refresh, logout };
}

/**
 * Wires the authentication flow onto an already-built collection:
 *
 *   - Login and refresh save the token when they respond with 2xx.
 *   - The login body references `{{authUsername}}` / `{{authPassword}}`.
 *   - Logout clears the token.
 *   - The flow is documented in the login description.
 *
 * Returns the applied flow, or `null` if the collection has no auth.
 */
export function applyAuthFlow(
  collection: PostmanCollection,
  options: IApplyAuthFlowOptions = {},
): IAuthFlow | null {
  const flow = detectAuthFlow(collection) ?? detectByName(collection, options.loginEndpointName);
  if (!flow) return null;

  const paths = options.tokenResponsePath?.trim()
    ? [options.tokenResponsePath.trim()]
    : TOKEN_RESPONSE_PATHS;

  // It is **added** to the array, not replaced. The builder has already put
  // assertions on each request, and assigning the whole array would wipe
  // them out exactly in the three endpoints where they are most needed:
  // those in the session cycle.
  if (flow.login) {
    flow.login.event = [...(flow.login.event ?? []), tokenCaptureEvent(paths)];
    flow.login.description = LOGIN_DESCRIPTION;
    attachCredentialTemplate(flow.login);
  }
  if (flow.refresh) {
    flow.refresh.event = [...(flow.refresh.event ?? []), tokenCaptureEvent(paths)];
  }
  if (flow.logout) {
    flow.logout.event = [...(flow.logout.event ?? []), tokenClearEvent()];
  }

  return flow;
}

/**
 * Variables the environment needs for the auth flow.
 * They are added only if the collection has login.
 */
export function authEnvironmentVariables(): Array<{
  key: string;
  value: string;
  type: string;
}> {
  return [
    { key: AUTH_USERNAME_VARIABLE, value: "", type: "secret" },
    { key: AUTH_PASSWORD_VARIABLE, value: "", type: "secret" },
    { key: AUTH_TOKEN_VARIABLE, value: "", type: "secret" },
  ];
}

// ---------------------------------------------------------------------------
// Postman scripts
// ---------------------------------------------------------------------------

const LOGIN_DESCRIPTION = [
  "Authentication in three steps:",
  "",
  `1. Fill in \`${AUTH_USERNAME_VARIABLE}\` and \`${AUTH_PASSWORD_VARIABLE}\` in the active environment.`,
  "2. Send this request.",
  `3. The token is stored in \`${AUTH_TOKEN_VARIABLE}\` automatically and every other endpoint uses it.`,
  "",
  "The token is written to the environment, so it survives closing Postman.",
].join("\n");

/**
 * Test event that extracts and stores the token.
 *
 * It writes to `pm.environment` (which persists between sessions), and falls
 * back to `pm.collectionVariables` if there is no active environment. The
 * `pm.test` makes the failure visible in the runner instead of silent.
 */
function tokenCaptureEvent(tokenPaths: ReadonlyArray<string>): NonNullable<
  PostmanItem["event"]
>[number] {
  const candidates = tokenPaths.map((p) => `  ${JSON.stringify(p)},`).join("\n");
  return {
    listen: "test",
    script: {
      type: "text/javascript",
      exec: [
        "const CANDIDATE_PATHS = [",
        candidates,
        "];",
        "",
        "function readPath(source, path) {",
        "  return path.split('.').reduce(function (acc, key) {",
        "    return acc === null || acc === undefined ? undefined : acc[key];",
        "  }, source);",
        "}",
        "",
        `pm.test('Login returns a token', function () {`,
        "  pm.expect(pm.response.code).to.be.oneOf([200, 201]);",
        "",
        "  let body;",
        "  try {",
        "    body = pm.response.json();",
        "  } catch (err) {",
        "    throw new Error('Response is not JSON: ' + pm.response.text().slice(0, 200));",
        "  }",
        "",
        "  let token;",
        "  for (const path of CANDIDATE_PATHS) {",
        "    const value = readPath(body, path);",
        "    if (typeof value === 'string' && value.length > 0) {",
        "      token = value;",
        "      break;",
        "    }",
        "  }",
        "",
        "  if (!token) {",
        "    throw new Error(",
        "      'Token not found in the response. Paths tried: ' +",
        "        CANDIDATE_PATHS.join(', ') +",
        `        '. Declare yours in config.tokenResponsePath.'`,
        "    );",
        "  }",
        "",
        "  // El environment persiste entre sesiones; las collection",
        "  // variables solo mientras la colección esté abierta.",
        "  if (pm.environment.name) {",
        `    pm.environment.set('${AUTH_TOKEN_VARIABLE}', token);`,
        "  } else {",
        `    pm.collectionVariables.set('${AUTH_TOKEN_VARIABLE}', token);`,
        "  }",
        "});",
      ],
    },
  };
}

/** Logout test event: leaves the token empty. */
function tokenClearEvent(): NonNullable<PostmanItem["event"]>[number] {
  return {
    listen: "test",
    script: {
      type: "text/javascript",
      exec: [
        "pm.test('Logout clears the token', function () {",
        `  pm.environment.set('${AUTH_TOKEN_VARIABLE}', '');`,
        `  pm.collectionVariables.set('${AUTH_TOKEN_VARIABLE}', '');`,
        "});",
      ],
    },
  };
}

// ---------------------------------------------------------------------------
// Login body
// ---------------------------------------------------------------------------

/**
 * Leaves the login body with credentials pointing to the environment,
 * **without replacing anything that is not a credential**.
 *
 * `useCredentialVariables` (the version it replaced) had a destructive case:
 * when the body did not include `username`/`email`/`password`, it overwrote
 * the entire body with an invented pair. That broke OAuth2 logins with
 * `grant_type`/`client_id`/`client_secret`, OTP flows, `tenant`/`apiKey`
 * forms, and any login the scanner had described with its real fields.
 *
 * This version (`a00012 S3.b`) follows three rules:
 *
 *   1. It only patches keys already in the body whose value is a `string`.
 *      Numeric, boolean, or `null` values are respected: the user probably
 *      knows what they are doing.
 *   2. It never replaces the entire body. If it finds no credentials, it
 *      leaves the body as-is and warns with `warnMissingCredentials`. The
 *      caller decides whether to show the warning to the user, skip login, or
 *      do something else.
 *   3. If it finds both keys (`username`/`password` or `email`/`password`), it
 *      writes the `{{...}}` placeholders over them. Everything else in the
 *      body (extra fields the scanner recognized) is preserved.
 *
 * For an empty or non-JSON login body, the behavior is identical: nothing
 * is invented, and a warning is emitted.
 */
function attachCredentialTemplate(login: PostmanItem): void {
  const request = login.request;
  if (!request) return;

  const parsed = parseJsonObject(request.body?.raw);
  if (!parsed) {
    warnMissingCredentials({
      reason: "no-json-body",
      path: request.url?.raw ?? "",
    });
    return;
  }

  const usernameKey = findStringField(parsed, USERNAME_FIELDS);
  const passwordKey = findStringField(parsed, PASSWORD_FIELDS);
  if (!usernameKey || !passwordKey) {
    warnMissingCredentials({
      reason: "no-credential-keys",
      path: request.url?.raw ?? "",
      keys: Object.keys(parsed),
    });
    return;
  }

  // Patches only credential keys and leaves everything else intact.
  parsed[usernameKey] = `{{${AUTH_USERNAME_VARIABLE}}}`;
  parsed[passwordKey] = `{{${AUTH_PASSWORD_VARIABLE}}}`;
  writeJsonBody(login, parsed);
}

/**
 * The first key in the object that appears in `candidates` (case-insensitive)
 * **and whose value is a `string`**. If the body has `email: 1` (a scanner
 * that filled it with a numeric placeholder), it is not considered a
 * credential: it is respected.
 */
function findStringField(
  body: Record<string, unknown>,
  candidates: ReadonlyArray<string>,
): string | undefined {
  for (const key of Object.keys(body)) {
    if (!candidates.includes(key.toLowerCase())) continue;
    if (typeof body[key] !== "string") continue;
    return key;
  }
  return undefined;
}

/**
 * Emits a structured warning when the login body does not expose recognizable
 * credentials. The function is exported for tests and so a caller can
 * redirect it if another sink is needed.
 *
 * The warning type lives in
 * `packages/contracts/interfaces/cli/auth-warning.interface.ts`; defining it
 * here would pull this service in just to type it, which is exactly what
 * `lint:contracts` prohibits.
 */
export function warnMissingCredentials(
  warning: Omit<IMissingCredentialsWarning, "kind">,
): void {
  const payload: IMissingCredentialsWarning = { kind: "missing-credentials", ...warning };
  console.warn(JSON.stringify(payload));
}

function parseJsonObject(raw: string | undefined): Record<string, unknown> | null {
  if (!raw) return null;
  try {
    const parsed: unknown = JSON.parse(raw);
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return null;
    return parsed as Record<string, unknown>;
  } catch {
    return null;
  }
}

function writeJsonBody(item: PostmanItem, body: Record<string, unknown>): void {
  if (!item.request) return;
  item.request.body = {
    mode: "raw",
    raw: JSON.stringify(body, null, 2),
    options: { raw: { language: "json" } },
  };
  const hasContentType = item.request.header.some(
    (h) => h.key.toLowerCase() === "content-type",
  );
  if (!hasContentType) {
    item.request.header.push({ key: "Content-Type", value: "application/json", type: "text" });
  }
}

// ---------------------------------------------------------------------------
// Traversal and matching
// ---------------------------------------------------------------------------

function* eachRequest(items: ReadonlyArray<PostmanItem>): Generator<PostmanItem> {
  for (const item of items) {
    if (item.item) {
      yield* eachRequest(item.item);
      continue;
    }
    if (item.request) yield item;
  }
}

function matchesAny(
  item: PostmanItem,
  patterns: ReadonlyArray<RegExp>,
  methods: ReadonlyArray<string>,
): boolean {
  const method = item.request?.method?.toUpperCase();
  if (!method || !methods.includes(method)) return false;
  const uri = stripQueryAndHost(item.request?.url?.raw ?? "");
  return patterns.some((p) => p.test(uri));
}

/** Removes the host (`{{baseUrl}}`) and the query to compare only the path. */
function stripQueryAndHost(raw: string): string {
  const withoutQuery = raw.split("?")[0] ?? "";
  return withoutQuery.replace(/^\{\{[^}]+\}\}/, "");
}

/**
 * Last resort: if the host declared `loginEndpointName`, it searches by exact
 * name. This covers projects with unconventional login routes.
 */
function detectByName(
  collection: PostmanCollection,
  loginEndpointName?: string,
): IAuthFlow | null {
  if (!loginEndpointName) return null;
  for (const item of eachRequest(collection.item ?? [])) {
    if (item.name === loginEndpointName) {
      return { login: item, refresh: null, logout: null };
    }
  }
  return null;
}

// ---------------------------------------------------------------------------
// Laravel-specific heuristic
// ---------------------------------------------------------------------------

/**
 * Heuristically detects the token dot-path in a Laravel project's
 * AuthController. It inspects the files
 * `app/Http/Controllers/*Auth*Controller.php` and searches for response
 * patterns. If it finds nothing, it returns undefined.
 */
export async function detectLaravelTokenPath(root: string): Promise<string | undefined> {
  const fs = await import("node:fs/promises");
  const path = await import("node:path");
  const ctlDir = path.join(root, "app/Http/Controllers");
  let entries: string[] = [];
  try {
    entries = await fs.readdir(ctlDir);
  } catch {
    return undefined;
  }
  const authFiles = entries.filter(
    (f) => /Auth(entic|oriz)?/i.test(f) && f.endsWith("Controller.php"),
  );
  for (const f of authFiles) {
    const text = await fs.readFile(path.join(ctlDir, f), "utf8").catch(() => "");
    // Common patterns: 'access_token' => $t, 'data' => ['token' => ...]
    if (/'access_token'\s*=>/.test(text) || /"access_token"\s*=>/.test(text))
      return "access_token";
    if (/'token'\s*=>\s*\$/.test(text) || /"token"\s*=>\s*\$/.test(text)) {
      // JWT: the token is usually at the root. Sanctum: usually data.token.
      // If there is 'data' => 'token', prefer data.token.
      if (/'data'\s*=>\s*\[[\s\S]*?'token'\s*=>/.test(text)) return "data.token";
      return "token";
    }
    if (/'data'\s*=>\s*\[[\s\S]*?'access_token'\s*=>/.test(text))
      return "data.access_token";
  }
  return undefined;
}

