/**
 * Exportadores a HAR 1.2 y a cURL.
 *
 * Los dos comparten la misma idea —una petición HTTP concreta, sin
 * envoltorio de herramienta— así que comparten fichero.
 *
 * **HAR es un formato de registro, no de plantilla.** Un `.har` de
 * verdad recoge peticiones que ya ocurrieron, con sus respuestas y sus
 * tiempos. Aquí no hay respuestas: nunca se ha ejecutado nada. La
 * especificación exige el objeto `response` en cada entrada, así que se
 * emite el que HAR define para "no se capturó respuesta" — `status: 0`,
 * cuerpo vacío, tamaños a -1. Es la convención del formato para
 * exactamente este caso, y es preferible a inventarse un 200 con un
 * cuerpo que nadie ha visto.
 *
 * Las variables se dejan **sin resolver** (`{{baseUrl}}`) a propósito.
 * Sustituirlas por el valor de la config produciría un fichero que
 * apunta a un entorno concreto, y quien importa un HAR en las DevTools
 * suele querer editarlo antes de lanzarlo.
 */
import type {
  IExportArtifact,
  IExportInput,
  IExportTarget,
} from "../../contracts/interfaces/core/export-target.interface.js";
import type { EndpointSpec } from "../../contracts/interfaces/core/postman.interface.js";

/** Las cabeceras que lleva una petición, según el esquema de auth. */
function headersFor(
  spec: EndpointSpec,
  auth: IExportInput["auth"],
): Array<{ name: string; value: string }> {
  const headers: Array<{ name: string; value: string }> = [
    { name: "Accept", value: "application/json" },
  ];
  if (spec.body !== undefined) {
    headers.push({ name: "Content-Type", value: "application/json" });
  }
  if (auth.type === "bearer") {
    headers.push({ name: "Authorization", value: "Bearer {{token}}" });
  }
  if (auth.type === "apikey" && auth.keyIn === "header") {
    headers.push({ name: auth.keyName ?? "X-API-Key", value: "{{apiKey}}" });
  }
  for (const h of spec.headers ?? []) headers.push({ name: h.key, value: h.value });
  return headers;
}

/** Serializa el catálogo a un registro HAR 1.2 sin respuestas. */
export class HarExporter implements IExportTarget {
  readonly format = "har";
  readonly summary = "HAR 1.2 (JSON) — DevTools and replay tools";

  serialize(input: IExportInput): IExportArtifact[] {
    const { specs, config, auth } = input;

    const entries = specs.map((spec) => {
      const headers = headersFor(spec, auth);
      const queryString = (spec.query ?? []).map((q) => ({
        name: q.key,
        value: q.value,
      }));
      return {
        startedDateTime: "1970-01-01T00:00:00.000Z",
        // -1 es lo que HAR usa para "no medido". Poner un 0 diría que
        // tardó cero, que es una afirmación distinta.
        time: -1,
        request: {
          method: spec.method,
          url: `{{baseUrl}}${spec.uri}`,
          httpVersion: "HTTP/1.1",
          cookies: [],
          headers,
          queryString,
          ...(spec.body !== undefined
            ? {
                postData: {
                  mimeType: "application/json",
                  text: JSON.stringify(spec.body),
                },
              }
            : {}),
          headersSize: -1,
          bodySize: -1,
        },
        // La entrada sin respuesta que define el formato. Ver la cabecera.
        response: {
          status: 0,
          statusText: "",
          httpVersion: "HTTP/1.1",
          cookies: [],
          headers: [],
          content: { size: 0, mimeType: "application/json" },
          redirectURL: "",
          headersSize: -1,
          bodySize: -1,
        },
        cache: {},
        timings: { send: -1, wait: -1, receive: -1 },
      };
    });

    const document = {
      log: {
        version: "1.2",
        creator: { name: "export-to-postman", version: "1.0.0" },
        comment: `${config.collectionName || config.name} — requests that were never executed`,
        entries,
      },
    };
    return [
      {
        path: `${config.name}.har`,
        content: JSON.stringify(document, null, 2) + "\n",
      },
    ];
  }
}

/** Escapa un valor para meterlo entre comillas simples en sh. */
function shellQuote(value: string): string {
  // En sh no hay escapes dentro de comillas simples: hay que cerrarlas,
  // meter una comilla escapada y volver a abrirlas.
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/** Serializa el catálogo a un script de shell con un cURL por endpoint. */
export class CurlExporter implements IExportTarget {
  readonly format = "curl";
  readonly summary = "Shell script with one cURL per endpoint";

  serialize(input: IExportInput): IExportArtifact[] {
    const { specs, config, auth } = input;
    const lines: string[] = [
      "#!/usr/bin/env sh",
      `# ${config.collectionName || config.name}`,
      "#",
      "# Generated by export-to-postman. Variables are read from the environment:",
      "# export whatever you need before running this.",
      "set -eu",
      "",
      `BASE_URL="\${BASE_URL:-${config.baseUrl}}"`,
    ];
    if (auth.type === "bearer") lines.push(`TOKEN="\${TOKEN:-}"`);
    if (auth.type === "apikey") lines.push(`API_KEY="\${API_KEY:-}"`);
    lines.push("");

    for (const spec of specs) {
      // Las variables de Postman pasan a variables de shell: un
      // `{{id}}` en la URL no lo entiende curl.
      const uri = spec.uri.replace(/\{\{([^}]+)\}\}/g, (_, name: string) => `\${${name}}`);
      lines.push(`# ${spec.method} ${spec.name}`);

      const args: string[] = [
        `-X ${spec.method}`,
        `"$BASE_URL${uri}"`,
        `-H ${shellQuote("Accept: application/json")}`,
      ];
      if (auth.type === "bearer") args.push(`-H "Authorization: Bearer $TOKEN"`);
      if (auth.type === "apikey" && auth.keyIn === "header") {
        args.push(`-H "${auth.keyName ?? "X-API-Key"}: $API_KEY"`);
      }
      for (const h of spec.headers ?? []) {
        args.push(`-H ${shellQuote(`${h.key}: ${h.value}`)}`);
      }
      if (spec.body !== undefined) {
        args.push(`-H ${shellQuote("Content-Type: application/json")}`);
        args.push(`-d ${shellQuote(JSON.stringify(spec.body))}`);
      }

      lines.push(`curl ${args.join(" \\\n  ")}`);
      lines.push("");
    }

    return [{ path: `${config.name}.curl.sh`, content: lines.join("\n") }];
  }
}
